[build]
  command="hugo --buildDrafts --gc"

[context.production.environment]
  HUGO_VERSION="0.91.1"
  HUGO_ENV="production"
  HUGO_ENABLEGITINFO="true"

[context.deploy-preview]
command = "hugo --buildDrafts --gc -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION="0.91.1"
  HUGO_ENABLEGITINFO="true"
